export const Q_FIELD_LABELS: Record<string, string> = {
  q1_main_bottleneck:       'Q1 — Principal gargalo',
  q2_lead_volume_month:     'Q2 — Volume mensal de leads',
  q3_team_size:             'Q3 — Tamanho da equipe',
  q4_crm_maturity:          'Q4 — Maturidade com CRM',
  q5_crm_name:              'Q5 — CRM utilizado',
  q6_trigger:               'Q6 — Gatilho de busca',
  q7_problem_impact:        'Q7 — Impacto do problema',
  q8_engagement_level:      'Q8 — Nível de engajamento',
  q9_decision_authority:    'Q9 — Autoridade de decisão',
  q10_stakeholders:         'Q10 — Stakeholders',
  q11_budget_approved:      'Q11 — Orçamento aprovado',
  q12_timeline:             'Q12 — Prazo',
  q13_urgency_reason:       'Q13 — Motivo da urgência',
  q14_data_ready:           'Q14 — Dados prontos',
  q15_minimum_volume:       'Q15 — Volume mínimo',
  q16_expected_roi:         'Q16 — ROI esperado',
  q17_objections:           'Q17 — Objeções',
  q18_real_fit:             'Q18 — Fit real',
  q19_qualification_status: 'Q19 — Status de qualificação',
  q20_rejection_reason:     'Q20 — Motivo de rejeição',
  q21_interest_level:       'Q21 — Nível de interesse',
  q22_close_probability:    'Q22 — Probabilidade de fechamento',
  q23_behavioral_tags:      'Q23 — Tags comportamentais',
  q24_last_update_by_agent: 'Q24 — Última atualização por agente',
  q25_disc_profile:         'Q25 — Perfil DISC',
  q26_disc_analysis:        'Q26 — Análise DISC',
};

export const Q_FIELD_ALIASES: Record<string, string[]> = {
  q1_main_bottleneck:       ['q1', 'gargalo', 'bottleneck', 'problema principal'],
  q2_lead_volume_month:     ['q2', 'volume', 'volumeleads', 'leads mes'],
  q3_team_size:             ['q3', 'equipe', 'teamsize', 'time'],
  q4_crm_maturity:          ['q4', 'maturidade', 'crmmaturity'],
  q5_crm_name:              ['q5', 'crmutilizado', 'crmname', 'sistema'],
  q6_trigger:               ['q6', 'gatilho', 'trigger'],
  q7_problem_impact:        ['q7', 'impacto', 'problemimpact'],
  q8_engagement_level:      ['q8', 'engajamento', 'engagementlevel'],
  q9_decision_authority:    ['q9', 'decisao', 'autoridade', 'authority'],
  q10_stakeholders:         ['q10', 'stakeholders', 'influenciadores'],
  q11_budget_approved:      ['q11', 'orcamento', 'budget'],
  q12_timeline:             ['q12', 'prazo', 'timeline'],
  q13_urgency_reason:       ['q13', 'urgencia', 'urgency'],
  q14_data_ready:           ['q14', 'dados prontos', 'dataready'],
  q15_minimum_volume:       ['q15', 'volume minimo', 'minimumvolume'],
  q16_expected_roi:         ['q16', 'roi', 'retorno'],
  q17_objections:           ['q17', 'objecoes', 'objections'],
  q18_real_fit:             ['q18', 'fit', 'realfit'],
  q19_qualification_status: ['q19', 'qualificacao', 'status qualificacao', 'qualification'],
  q20_rejection_reason:     ['q20', 'rejeicao', 'rejection'],
  q21_interest_level:       ['q21', 'interesse', 'interest'],
  q22_close_probability:    ['q22', 'probabilidade', 'fechamento', 'probability'],
  q23_behavioral_tags:      ['q23', 'tags', 'comportamental', 'behavioral'],
  q24_last_update_by_agent: ['q24', 'ultima atualizacao', 'agente'],
  q25_disc_profile:         ['q25', 'disc', 'perfil disc', 'discprofile'],
  q26_disc_analysis:        ['q26', 'analise disc', 'discanalysis'],
};
