-- Blindagem de segurança aplicada em 08/09/2026 no projeto maigkwlgzinykfvemexf.
-- Origem: Security Advisor do Supabase (125 erros) + dois buracos que ele não reporta:
--   cadastro público aberto no Auth e políticas que bastava estar logado para passar.
-- Aplicada via Management API (este projeto não usa supabase_migrations.schema_migrations).

-- Security Advisor do Supabase — projeto Minimal (maigkwlgzinykfvemexf)
-- Antes: 89 tabelas sem RLS + 38 políticas abertas ao role public → a anon key do frontend lia e
-- escrevia tudo (clientes, leads, usuários e credenciais de Klaviyo/OpenAI/WhatsApp).
-- Depois: RLS em todas as tabelas, acesso só para usuário logado, escrita de credenciais só admin/gestor.
-- As políticas granulares que já existiam (por dono, por time, delete só admin) são preservadas:
-- só preenchemos os comandos que ficariam sem nenhuma política.
BEGIN;

-- ── 1. Políticas nomeadas "authenticated_*" que na verdade valiam para o role public (inclui anon)
DROP POLICY IF EXISTS "System can insert audit log" ON public."adm_audit_log";
CREATE POLICY "System can insert audit log" ON public."adm_audit_log" FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."ai_agents_score_matrix";
CREATE POLICY "authenticated_read" ON public."ai_agents_score_matrix" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."ai_agents_score_matrix";
CREATE POLICY "authenticated_write" ON public."ai_agents_score_matrix" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."ai_agents_steps_history";
CREATE POLICY "authenticated_read" ON public."ai_agents_steps_history" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."ai_agents_steps_history";
CREATE POLICY "authenticated_write" ON public."ai_agents_steps_history" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_companies";
CREATE POLICY "authenticated_read" ON public."clients_companies" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."clients_companies";
CREATE POLICY "authenticated_write" ON public."clients_companies" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_people_companies";
CREATE POLICY "authenticated_read" ON public."clients_people_companies" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."clients_people_companies";
CREATE POLICY "authenticated_write" ON public."clients_people_companies" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_people_updates";
CREATE POLICY "authenticated_read" ON public."clients_people_updates" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."clients_people_updates";
CREATE POLICY "authenticated_write" ON public."clients_people_updates" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_loss_reasons";
CREATE POLICY "authenticated_read" ON public."leads_loss_reasons" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_loss_reasons";
CREATE POLICY "authenticated_write" ON public."leads_loss_reasons" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_pipelines";
CREATE POLICY "authenticated_read" ON public."leads_pipelines" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_read_duplication_rules" ON public."leads_stage_duplication_rules";
CREATE POLICY "authenticated_read_duplication_rules" ON public."leads_stage_duplication_rules" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_stages";
CREATE POLICY "authenticated_read" ON public."leads_stages" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_updates";
CREATE POLICY "authenticated_read" ON public."leads_updates" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_updates";
CREATE POLICY "authenticated_write" ON public."leads_updates" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_delete" ON public."messages";
CREATE POLICY "authenticated_delete" ON public."messages" FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_insert" ON public."messages";
CREATE POLICY "authenticated_insert" ON public."messages" FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_update" ON public."messages";
CREATE POLICY "authenticated_update" ON public."messages" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."score_matrix";
CREATE POLICY "authenticated_read" ON public."score_matrix" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."score_matrix";
CREATE POLICY "authenticated_write" ON public."score_matrix" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."sends";
CREATE POLICY "authenticated_read" ON public."sends" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."sends";
CREATE POLICY "authenticated_write" ON public."sends" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."sends_contacts";
CREATE POLICY "authenticated_read" ON public."sends_contacts" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."sends_contacts";
CREATE POLICY "authenticated_write" ON public."sends_contacts" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."settings";
CREATE POLICY "authenticated_read" ON public."settings" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_system_modules";
CREATE POLICY "authenticated_read" ON public."settings_system_modules" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_system_modules";
CREATE POLICY "authenticated_write" ON public."settings_system_modules" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_teams";
CREATE POLICY "authenticated_read" ON public."settings_teams" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_teams";
CREATE POLICY "authenticated_write" ON public."settings_teams" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_users_teams";
CREATE POLICY "authenticated_read" ON public."settings_users_teams" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_users_teams";
CREATE POLICY "authenticated_write" ON public."settings_users_teams" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."webhooks";
CREATE POLICY "authenticated_read" ON public."webhooks" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."webhooks";
CREATE POLICY "authenticated_write" ON public."webhooks" FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated_read" ON public."whatsapp_templates";
CREATE POLICY "authenticated_read" ON public."whatsapp_templates" FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated_write" ON public."whatsapp_templates";
CREATE POLICY "authenticated_write" ON public."whatsapp_templates" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Leituras abertas a anon em tabelas com segredo. Os dois módulos que as usavam (FORM PRO e
-- Agendamentos) estão desativados neste tenant. form_pro_forms expõe webhook_secret; settings
-- expõe apify_token, google_client_secret, apollo/pdl/explorium (hoje nulos, mas o buraco é o mesmo).
-- Mantidas de propósito: booking_rule_sets/booking_rules (só is_active, sem segredo),
-- auth_events_log e data_deletion_requests (INSERT apenas, sem leitura).
DROP POLICY IF EXISTS "allow_anon_read_form_pro_forms" ON public."form_pro_forms";
DROP POLICY IF EXISTS "allow_anon_read_settings" ON public."settings";

-- ── 2. Preenche só os comandos que ficariam sem política nenhuma
CREATE POLICY "authenticated_read" ON public."canned_responses" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."canned_responses" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."clients_people" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."clients_people" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "authenticated_update" ON public."clients_people" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."crm_tenants" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."data_export_jobs" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."elevenlabs_agents" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."elevenlabs_agents" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."elevenlabs_voices" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."elevenlabs_voices" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."email_templates" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."email_templates" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."followup_queue" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."followup_queue" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."form_pro_forms" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."form_pro_forms" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."form_pro_forms" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."form_pro_forms" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "service_role_only" ON public."form_pro_rate_limits" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."form_pro_submissions" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."form_pro_submissions" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."kiwify_connections" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."kiwify_connections" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."kiwify_connections" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."kiwify_connections" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."kiwify_event_mappings" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."kiwify_event_mappings" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."kiwify_lead_products" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."kiwify_lead_products" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."kiwify_message_automations" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."kiwify_message_automations" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."kiwify_message_jobs" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."kiwify_webhook_events" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."lead_field_definitions" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."lead_field_definitions" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."lead_field_values" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."lead_field_values" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."lead_tags" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."lead_tags" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."lead_types" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."lead_types" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."leads" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."leads" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "authenticated_update" ON public."leads" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."leads_files" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."leads_files" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."leads_notes" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."leads_notes" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_insert" ON public."leads_pipelines" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "authenticated_update" ON public."leads_pipelines" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_delete" ON public."leads_pipelines" FOR DELETE TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."leads_stage_duplication_rules" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "authenticated_update" ON public."leads_stage_duplication_rules" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_delete" ON public."leads_stage_duplication_rules" FOR DELETE TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."leads_stages" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "authenticated_update" ON public."leads_stages" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_delete" ON public."leads_stages" FOR DELETE TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON public."leads_stages_followups" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."leads_stages_followups" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."leads_tags" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."leads_tags" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."lgpd_anonymization_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."meeting_followup_queue" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."meeting_followup_queue" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."meeting_records" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."meeting_records" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."meetings" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."meetings" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."meetings_followups" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."meetings_followups" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."message_buffer" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."meta_lead_form_pages" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."meta_lead_form_pages" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."meta_lead_form_pages" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."meta_lead_form_pages" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."meta_lead_forms" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."meta_lead_forms" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."mfa_recovery_codes" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."notifications" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."notifications" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."omni_channel_alerts" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."omni_channel_configs" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."omni_channel_configs" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."omni_channel_configs" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."omni_channel_configs" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "service_role_only" ON public."omni_delivery_dead_letter" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."omni_outbound_webhooks" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."omni_outbound_webhooks" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."score_categories" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."score_categories" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."score_category_items" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."score_category_items" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."score_settings" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."score_settings" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "service_role_only" ON public."secret_access_log" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."sends_import_sessions" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."sends_import_sessions" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_insert" ON public."settings" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."settings" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."settings" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."settings_audit_log" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."settings_audit_log" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."settings_elevenlabs" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."settings_elevenlabs" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."settings_elevenlabs" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."settings_elevenlabs" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."settings_omni_new_contact" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."settings_omni_new_contact" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."settings_schedules" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."settings_schedules" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."settings_teams_tags" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."settings_teams_tags" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_read" ON public."settings_users" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."settings_users" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."settings_users" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."settings_users" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."settings_whatsapp_channels" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."settings_whatsapp_channels" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."settings_whatsapp_channels" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."settings_whatsapp_channels" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."tenant_api_keys" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."tenant_api_keys" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."tenant_api_keys" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."tenant_api_keys" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."tenant_role_permissions" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."tenant_role_permissions" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."tenant_role_permissions" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."tenant_role_permissions" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."tenant_roles" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."tenant_roles" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."tenant_roles" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."tenant_roles" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."user_calcom_connections" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."user_calcom_connections" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."user_calcom_connections" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."user_calcom_connections" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."user_calendar_connections" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_insert" ON public."user_calendar_connections" FOR INSERT TO authenticated WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_update" ON public."user_calendar_connections" FOR UPDATE TO authenticated USING (is_admin_or_manager()) WITH CHECK (is_admin_or_manager());
CREATE POLICY "authenticated_delete" ON public."user_calendar_connections" FOR DELETE TO authenticated USING (is_admin_or_manager());
CREATE POLICY "authenticated_read" ON public."user_notification_preferences" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_write" ON public."user_notification_preferences" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_update" ON public."webhook_logs" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_delete" ON public."webhook_logs" FOR DELETE TO authenticated USING (true);

-- ── 3. Liga a RLS
ALTER TABLE public."canned_responses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."clients_companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."clients_people" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."clients_people_companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."clients_people_updates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conversion_event_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conversion_events_queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conversion_platform_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conversion_stage_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_tenants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."data_deletion_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."data_export_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."elevenlabs_agents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."elevenlabs_voices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."email_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."followup_queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."form_pro_forms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."form_pro_rate_limits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."form_pro_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."inbound_webhooks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."instagram_automation_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."instagram_automations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kiwify_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kiwify_event_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kiwify_lead_products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kiwify_message_automations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kiwify_message_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kiwify_webhook_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lead_field_definitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lead_field_values" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lead_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lead_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_loss_reasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_pipelines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_stage_duplication_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_stages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_stages_followups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads_updates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lgpd_anonymization_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."meeting_followup_queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."meeting_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."meetings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."meetings_followups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."message_buffer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."meta_lead_form_pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."meta_lead_forms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."mfa_recovery_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."omni_channel_alerts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."omni_channel_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."omni_delivery_dead_letter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."omni_outbound_webhooks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."schedule_automations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."score_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."score_category_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."score_matrix" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."score_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."secret_access_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sends" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sends_contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sends_import_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_ai_providers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_business_hours" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_elevenlabs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_omni_new_contact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_schedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_system_modules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_teams_pipelines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_teams_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_users_teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings_whatsapp_channels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tenant_api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tenant_role_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tenant_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_calcom_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_calendar_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_notification_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."webhook_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."webhooks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."whatsapp_templates" ENABLE ROW LEVEL SECURITY;

-- ── 4. Views paravam de respeitar a RLS de quem chama (SECURITY DEFINER)
ALTER VIEW public.followup_queue_legacy SET (security_invoker = on);
ALTER VIEW public.meta_lead_form_pages_safe SET (security_invoker = on);

COMMIT;

-- Parte 2: funções — search_path fixo e sem execução por visitante anônimo
BEGIN;

-- search_path mutável: uma função SECURITY DEFINER sem search_path fixo pode ser
-- sequestrada por um objeto plantado num schema que venha antes no caminho de busca.
ALTER FUNCTION adm_clients_set_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION adm_timeout_stuck_jobs() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION assign_booking_rule_set_url_id() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION audit_value(text,text) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION cleanup_agent_history(uuid,integer) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION find_duplicate_person(uuid,text,text,text,text,text) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION fn_queue_conversion_booking() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION fn_queue_conversion_event() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION fn_schedule_automation_on_status_change() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION get_insights_context(timestamp with time zone,timestamp with time zone,uuid) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION get_omni_contacts(text,text,text,text,text,text,text,text,integer,integer,text,text) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION import_pessoa_with_flexible_lead(jsonb,uuid,uuid,text) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION increment_field(text,text,uuid,integer) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION is_sensitive_column(text) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION merge_persons(uuid,uuid) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION normalize_br_phone(text) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION restore_agent_version(uuid,uuid) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION score_settings_set_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION seed_default_tenant_roles(uuid) SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_adm_clients_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_dead_letter_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_elevenlabs_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_instagram_automation_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_omni_channel_configs_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_omni_outbound_webhooks_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION set_schedule_automation_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION settings_ai_providers_set_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION settings_audit_trigger_fn() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION settings_users_sync_admin_flag() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION settings_whatsapp_channels_set_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION trg_advance_stage_on_first_ai_message() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION trg_auto_merge_on_identity() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION trg_cleanup_agent_history() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION trg_normalize_whatsapp_on_write() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION trigger_ai_on_buffer_insert() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION update_bi_ad_tables_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION update_bi_sdr_targets_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION update_lp_tables_updated_at() SET search_path = public, extensions, pg_temp;
ALTER FUNCTION update_sends_import_sessions_updated_at() SET search_path = public, extensions, pg_temp;

-- EXECUTE por anon em funções SECURITY DEFINER (rodam com privilégio do dono).
-- Preservadas para as páginas públicas: book_meeting, get_booking_session, get_public_settings.
REVOKE EXECUTE ON FUNCTION add_lead_to_pipeline(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION adm_client_decrypted_secrets(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION adm_clients_secrets_status() FROM anon;
REVOKE EXECUTE ON FUNCTION adm_timeout_stuck_jobs() FROM anon;
REVOKE EXECUTE ON FUNCTION ai_agent_watchdog() FROM anon;
REVOKE EXECUTE ON FUNCTION anonymize_person(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION app_decrypt_secret(text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION app_encrypt_secret(text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION append_crm_field_value(uuid,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION assign_lead_round_robin(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION auto_pause_ai_on_human_message() FROM anon;
REVOKE EXECUTE ON FUNCTION bump_clients_people_on_message() FROM anon;
REVOKE EXECUTE ON FUNCTION check_bi_voice_beta_update() FROM anon;
REVOKE EXECUTE ON FUNCTION claim_followup_queue_batch(integer) FROM anon;
REVOKE EXECUTE ON FUNCTION claim_pending_messages(integer,integer,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION cleanup_agent_history(uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION cleanup_auth_login_attempts() FROM anon;
REVOKE EXECUTE ON FUNCTION cleanup_bi_voice_token_log() FROM anon;
REVOKE EXECUTE ON FUNCTION create_tenant_user(text,text,text,text,text,boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION decrypt_elevenlabs_key(text) FROM anon;
REVOKE EXECUTE ON FUNCTION disable_ai_on_atendimento_humano() FROM anon;
REVOKE EXECUTE ON FUNCTION dispatch_new_lead_webhooks() FROM anon;
REVOKE EXECUTE ON FUNCTION duplicate_lead_on_stage_enter() FROM anon;
REVOKE EXECUTE ON FUNCTION encrypt_elevenlabs_key(text) FROM anon;
REVOKE EXECUTE ON FUNCTION find_duplicate_person(uuid,text,text,text,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION fn_queue_conversion_booking() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_queue_conversion_event() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_schedule_automation_on_status_change() FROM anon;
REVOKE EXECUTE ON FUNCTION get_active_ai_provider_key(text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_available_slots(uuid,date,text,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_booking_eligible_user_ids(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_booking_eligible_user_ids(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_current_settings_user_id() FROM anon;
REVOKE EXECUTE ON FUNCTION get_current_user_tenant_id() FROM anon;
REVOKE EXECUTE ON FUNCTION get_insights_context(timestamp with time zone,timestamp with time zone,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION handle_meeting_followup_queue() FROM anon;
REVOKE EXECUTE ON FUNCTION import_pessoa_with_flexible_lead(jsonb,uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION increment_field(text,text,uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION is_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION is_admin_or_gestor() FROM anon;
REVOKE EXECUTE ON FUNCTION is_admin_or_manager() FROM anon;
REVOKE EXECUTE ON FUNCTION lead_pipeline_accessible_to_current_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION link_pipeline_to_kiwify_product(uuid,text,text,boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION mark_all_notifications_read() FROM anon;
REVOKE EXECUTE ON FUNCTION mark_conversation_read(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION mark_notification_read(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION merge_persons(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION mfa_recovery_consume(text) FROM anon;
REVOKE EXECUTE ON FUNCTION mfa_recovery_generate() FROM anon;
REVOKE EXECUTE ON FUNCTION move_lead_to_stage(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION notify_closer_on_meeting_scheduled() FROM anon;
REVOKE EXECUTE ON FUNCTION notify_lead_stage_changed() FROM anon;
REVOKE EXECUTE ON FUNCTION person_conversation_accessible_to_current_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION process_message_buffer() FROM anon;
REVOKE EXECUTE ON FUNCTION propagate_message_status_to_sends() FROM anon;
REVOKE EXECUTE ON FUNCTION recalc_unread_count(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION release_stale_ai_locks() FROM anon;
REVOKE EXECUTE ON FUNCTION reorder_leads_stage(uuid,uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION reset_stale_sending_messages() FROM anon;
REVOKE EXECUTE ON FUNCTION restore_agent_version(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION save_agent_complete(uuid,jsonb,jsonb,jsonb,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION secure_http_post(text,text,jsonb,text) FROM anon;
REVOKE EXECUTE ON FUNCTION set_booking_lead_email(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION settings_audit_trigger_fn() FROM anon;
REVOKE EXECUTE ON FUNCTION settings_users_set_mfa_grace() FROM anon;
REVOKE EXECUTE ON FUNCTION site_lead_gate_create_lead(text,text,uuid,uuid,text,text,text,text,text,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION sync_active_channel_from_message() FROM anon;
REVOKE EXECUTE ON FUNCTION sync_custom_domain_to_adm(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION sync_service_role_from_vault() FROM anon;
REVOKE EXECUTE ON FUNCTION tag_accessible_to_current_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION track_leads_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_advance_stage_on_first_ai_message() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_auto_merge_on_identity() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_cleanup_agent_history() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_followup_retry_worker() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_followup_worker() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_fwup01_smoke_test() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_google_calendar_sync() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_instagram_token_refresh() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_omni_channel_health_check() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_omni_delivery_engine() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_omni_retry_dead_letter() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_process_meeting_followups() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_sends_dispatch_batch() FROM anon;
REVOKE EXECUTE ON FUNCTION trigger_zoom_token_refresh() FROM anon;
REVOKE EXECUTE ON FUNCTION unlink_pipeline_kiwify_product(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION update_meeting(uuid,text,timestamp with time zone,integer,text) FROM anon;
REVOKE EXECUTE ON FUNCTION update_qualification_field(uuid,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION upsert_crm_field_value(uuid,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION upsert_field_value(uuid,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION user_has_tenant_access(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION validate_stage_ids(uuid[]) FROM anon;

COMMIT;

-- Parte 3: tirar do role PUBLIC (que inclui anon) o EXECUTE das funções SECURITY DEFINER,
-- devolvendo o acesso explicitamente a quem o app usa (authenticated e service_role).
-- Preservadas para as páginas públicas: book_meeting, get_booking_session, get_public_settings.
BEGIN;

REVOKE EXECUTE ON FUNCTION add_lead_to_pipeline(uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION add_lead_to_pipeline(uuid,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION adm_client_decrypted_secrets(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION adm_client_decrypted_secrets(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION adm_clients_secrets_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION adm_clients_secrets_status() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION adm_timeout_stuck_jobs() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION adm_timeout_stuck_jobs() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION ai_agent_watchdog() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION ai_agent_watchdog() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION anonymize_person(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION anonymize_person(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION app_decrypt_secret(text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION app_decrypt_secret(text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION app_encrypt_secret(text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION app_encrypt_secret(text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION append_crm_field_value(uuid,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION append_crm_field_value(uuid,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION assign_lead_round_robin(uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION assign_lead_round_robin(uuid,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION auto_pause_ai_on_human_message() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION auto_pause_ai_on_human_message() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION bump_clients_people_on_message() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION bump_clients_people_on_message() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION check_bi_voice_beta_update() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION check_bi_voice_beta_update() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION claim_followup_queue_batch(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION claim_followup_queue_batch(integer) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION claim_pending_messages(integer,integer,uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION claim_pending_messages(integer,integer,uuid,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION cleanup_agent_history(uuid,integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION cleanup_agent_history(uuid,integer) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION cleanup_auth_login_attempts() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION cleanup_auth_login_attempts() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION cleanup_bi_voice_token_log() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION cleanup_bi_voice_token_log() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION create_tenant_user(text,text,text,text,text,boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION create_tenant_user(text,text,text,text,text,boolean) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION decrypt_elevenlabs_key(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION decrypt_elevenlabs_key(text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION disable_ai_on_atendimento_humano() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION disable_ai_on_atendimento_humano() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION dispatch_new_lead_webhooks() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION dispatch_new_lead_webhooks() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION duplicate_lead_on_stage_enter() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION duplicate_lead_on_stage_enter() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION encrypt_elevenlabs_key(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION encrypt_elevenlabs_key(text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION enqueue_stage_followups(uuid,boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION enqueue_stage_followups(uuid,boolean) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION find_duplicate_person(uuid,text,text,text,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION find_duplicate_person(uuid,text,text,text,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION fn_queue_conversion_booking() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION fn_queue_conversion_booking() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION fn_queue_conversion_event() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION fn_queue_conversion_event() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION fn_schedule_automation_on_status_change() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION fn_schedule_automation_on_status_change() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_active_ai_provider_key(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_active_ai_provider_key(text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_available_slots(uuid,date,text,integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_available_slots(uuid,date,text,integer) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_booking_eligible_user_ids(uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_booking_eligible_user_ids(uuid,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_booking_eligible_user_ids(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_booking_eligible_user_ids(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_current_settings_user_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_current_settings_user_id() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_current_user_tenant_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_current_user_tenant_id() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION get_insights_context(timestamp with time zone,timestamp with time zone,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_insights_context(timestamp with time zone,timestamp with time zone,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION handle_meeting_followup_queue() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION handle_meeting_followup_queue() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION import_pessoa_with_flexible_lead(jsonb,uuid,uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION import_pessoa_with_flexible_lead(jsonb,uuid,uuid,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION increment_field(text,text,uuid,integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION increment_field(text,text,uuid,integer) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION is_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION is_admin() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION is_admin_or_gestor() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION is_admin_or_gestor() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION is_admin_or_manager() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION is_admin_or_manager() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION lead_pipeline_accessible_to_current_user(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION lead_pipeline_accessible_to_current_user(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION link_pipeline_to_kiwify_product(uuid,text,text,boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION link_pipeline_to_kiwify_product(uuid,text,text,boolean) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION mark_all_notifications_read() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION mark_all_notifications_read() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION mark_conversation_read(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION mark_conversation_read(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION mark_notification_read(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION mark_notification_read(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION merge_persons(uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION merge_persons(uuid,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION mfa_recovery_consume(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION mfa_recovery_consume(text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION mfa_recovery_generate() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION mfa_recovery_generate() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION move_lead_to_stage(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION move_lead_to_stage(uuid,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION notify_closer_on_meeting_scheduled() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION notify_closer_on_meeting_scheduled() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION notify_lead_stage_changed() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION notify_lead_stage_changed() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION person_conversation_accessible_to_current_user(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION person_conversation_accessible_to_current_user(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION process_message_buffer() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION process_message_buffer() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION propagate_message_status_to_sends() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION propagate_message_status_to_sends() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION purge_tracked_click_pii() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION purge_tracked_click_pii() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION recalc_unread_count(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION recalc_unread_count(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION record_tracked_click(text,boolean,text,text,text,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION record_tracked_click(text,boolean,text,text,text,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION release_stale_ai_locks() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION release_stale_ai_locks() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION reorder_leads_stage(uuid,uuid,integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION reorder_leads_stage(uuid,uuid,integer) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION reset_stale_sending_messages() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION reset_stale_sending_messages() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION restore_agent_version(uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION restore_agent_version(uuid,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION save_agent_complete(uuid,jsonb,jsonb,jsonb,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION save_agent_complete(uuid,jsonb,jsonb,jsonb,uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION secure_http_post(text,text,jsonb,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION secure_http_post(text,text,jsonb,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION set_booking_lead_email(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION set_booking_lead_email(uuid,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION settings_audit_trigger_fn() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION settings_audit_trigger_fn() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION settings_users_set_mfa_grace() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION settings_users_set_mfa_grace() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION site_lead_gate_create_lead(text,text,uuid,uuid,text,text,text,text,text,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION site_lead_gate_create_lead(text,text,uuid,uuid,text,text,text,text,text,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION sync_active_channel_from_message() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION sync_active_channel_from_message() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION sync_custom_domain_to_adm(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION sync_custom_domain_to_adm(uuid,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION sync_service_role_from_vault() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION sync_service_role_from_vault() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION tag_accessible_to_current_user(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION tag_accessible_to_current_user(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION track_leads_changes() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION track_leads_changes() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trg_advance_stage_on_first_ai_message() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trg_advance_stage_on_first_ai_message() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trg_auto_merge_on_identity() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trg_auto_merge_on_identity() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trg_cleanup_agent_history() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trg_cleanup_agent_history() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_followup_retry_worker() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_followup_retry_worker() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_followup_worker() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_followup_worker() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_fwup01_smoke_test() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_fwup01_smoke_test() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_google_calendar_sync() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_google_calendar_sync() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_instagram_token_refresh() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_instagram_token_refresh() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_omni_channel_health_check() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_omni_channel_health_check() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_omni_delivery_engine() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_omni_delivery_engine() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_omni_retry_dead_letter() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_omni_retry_dead_letter() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_process_meeting_followups() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_process_meeting_followups() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_sends_dispatch_batch() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_sends_dispatch_batch() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION trigger_zoom_token_refresh() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trigger_zoom_token_refresh() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION unlink_pipeline_kiwify_product(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION unlink_pipeline_kiwify_product(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION update_meeting(uuid,text,timestamp with time zone,integer,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION update_meeting(uuid,text,timestamp with time zone,integer,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION update_qualification_field(uuid,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION update_qualification_field(uuid,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION upsert_crm_field_value(uuid,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION upsert_crm_field_value(uuid,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION upsert_field_value(uuid,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION upsert_field_value(uuid,text,text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION user_has_tenant_access(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION user_has_tenant_access(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION validate_stage_ids(uuid[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION validate_stage_ids(uuid[]) TO authenticated, service_role;

COMMIT;

-- Parte 4: 'estar logado' não basta — precisa ser usuário ativo do CRM.
-- Sem isso, qualquer conta criada no Auth (o cadastro público estava aberto) leria tudo.
BEGIN;

CREATE OR REPLACE FUNCTION public.is_app_user() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT EXISTS (SELECT 1 FROM public.settings_users su
                 WHERE su.auth_user_id = auth.uid() AND su.active AND su.deleted_at IS NULL);
$$;
REVOKE EXECUTE ON FUNCTION public.is_app_user() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_app_user() TO authenticated, service_role;

DROP POLICY IF EXISTS "System can insert audit log" ON public."adm_audit_log";
CREATE POLICY "System can insert audit log" ON public."adm_audit_log" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."ai_agents_score_matrix";
CREATE POLICY "authenticated_read" ON public."ai_agents_score_matrix" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."ai_agents_score_matrix";
CREATE POLICY "authenticated_write" ON public."ai_agents_score_matrix" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."ai_agents_steps_history";
CREATE POLICY "authenticated_read" ON public."ai_agents_steps_history" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."ai_agents_steps_history";
CREATE POLICY "authenticated_write" ON public."ai_agents_steps_history" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "bi_ad_accounts_select" ON public."bi_ad_accounts";
CREATE POLICY "bi_ad_accounts_select" ON public."bi_ad_accounts" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "bi_ad_campaigns_select" ON public."bi_ad_campaigns";
CREATE POLICY "bi_ad_campaigns_select" ON public."bi_ad_campaigns" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "bi_ad_daily_stats_select" ON public."bi_ad_daily_stats";
CREATE POLICY "bi_ad_daily_stats_select" ON public."bi_ad_daily_stats" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "bi_ad_spend_all" ON public."bi_ad_spend";
CREATE POLICY "bi_ad_spend_all" ON public."bi_ad_spend" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "bi_settings_all" ON public."bi_settings";
CREATE POLICY "bi_settings_all" ON public."bi_settings" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."canned_responses";
CREATE POLICY "authenticated_read" ON public."canned_responses" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."canned_responses";
CREATE POLICY "authenticated_write" ON public."canned_responses" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_companies";
CREATE POLICY "authenticated_read" ON public."clients_companies" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."clients_companies";
CREATE POLICY "authenticated_write" ON public."clients_companies" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_insert" ON public."clients_people";
CREATE POLICY "authenticated_insert" ON public."clients_people" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_people";
CREATE POLICY "authenticated_read" ON public."clients_people" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."clients_people";
CREATE POLICY "authenticated_update" ON public."clients_people" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_people_companies";
CREATE POLICY "authenticated_read" ON public."clients_people_companies" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."clients_people_companies";
CREATE POLICY "authenticated_write" ON public."clients_people_companies" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."clients_people_updates";
CREATE POLICY "authenticated_read" ON public."clients_people_updates" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."clients_people_updates";
CREATE POLICY "authenticated_write" ON public."clients_people_updates" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_full_access_deletion_requests" ON public."data_deletion_requests";
CREATE POLICY "authenticated_full_access_deletion_requests" ON public."data_deletion_requests" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."elevenlabs_agents";
CREATE POLICY "authenticated_read" ON public."elevenlabs_agents" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."elevenlabs_agents";
CREATE POLICY "authenticated_write" ON public."elevenlabs_agents" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."elevenlabs_voices";
CREATE POLICY "authenticated_read" ON public."elevenlabs_voices" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."elevenlabs_voices";
CREATE POLICY "authenticated_write" ON public."elevenlabs_voices" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."email_templates";
CREATE POLICY "authenticated_read" ON public."email_templates" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."email_templates";
CREATE POLICY "authenticated_write" ON public."email_templates" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."followup_queue";
CREATE POLICY "authenticated_read" ON public."followup_queue" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."followup_queue";
CREATE POLICY "authenticated_write" ON public."followup_queue" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."form_pro_forms";
CREATE POLICY "authenticated_read" ON public."form_pro_forms" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."form_pro_submissions";
CREATE POLICY "authenticated_read" ON public."form_pro_submissions" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."form_pro_submissions";
CREATE POLICY "authenticated_write" ON public."form_pro_submissions" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_all" ON public."instagram_automation_log";
CREATE POLICY "authenticated_all" ON public."instagram_automation_log" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_all" ON public."instagram_automations";
CREATE POLICY "authenticated_all" ON public."instagram_automations" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."kiwify_connections";
CREATE POLICY "authenticated_read" ON public."kiwify_connections" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."kiwify_event_mappings";
CREATE POLICY "authenticated_read" ON public."kiwify_event_mappings" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."kiwify_event_mappings";
CREATE POLICY "authenticated_write" ON public."kiwify_event_mappings" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."kiwify_lead_products";
CREATE POLICY "authenticated_read" ON public."kiwify_lead_products" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."kiwify_lead_products";
CREATE POLICY "authenticated_write" ON public."kiwify_lead_products" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."kiwify_message_automations";
CREATE POLICY "authenticated_read" ON public."kiwify_message_automations" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."kiwify_message_automations";
CREATE POLICY "authenticated_write" ON public."kiwify_message_automations" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."lead_field_definitions";
CREATE POLICY "authenticated_read" ON public."lead_field_definitions" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."lead_field_definitions";
CREATE POLICY "authenticated_write" ON public."lead_field_definitions" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."lead_field_values";
CREATE POLICY "authenticated_read" ON public."lead_field_values" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."lead_field_values";
CREATE POLICY "authenticated_write" ON public."lead_field_values" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."lead_tags";
CREATE POLICY "authenticated_read" ON public."lead_tags" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."lead_tags";
CREATE POLICY "authenticated_write" ON public."lead_tags" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."lead_types";
CREATE POLICY "authenticated_read" ON public."lead_types" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."lead_types";
CREATE POLICY "authenticated_write" ON public."lead_types" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_insert" ON public."leads";
CREATE POLICY "authenticated_insert" ON public."leads" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads";
CREATE POLICY "authenticated_read" ON public."leads" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."leads";
CREATE POLICY "authenticated_update" ON public."leads" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_files";
CREATE POLICY "authenticated_read" ON public."leads_files" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_files";
CREATE POLICY "authenticated_write" ON public."leads_files" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_loss_reasons";
CREATE POLICY "authenticated_read" ON public."leads_loss_reasons" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_loss_reasons";
CREATE POLICY "authenticated_write" ON public."leads_loss_reasons" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_notes";
CREATE POLICY "authenticated_read" ON public."leads_notes" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_notes";
CREATE POLICY "authenticated_write" ON public."leads_notes" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_delete" ON public."leads_pipelines";
CREATE POLICY "authenticated_delete" ON public."leads_pipelines" FOR DELETE TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_insert" ON public."leads_pipelines";
CREATE POLICY "authenticated_insert" ON public."leads_pipelines" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_pipelines";
CREATE POLICY "authenticated_read" ON public."leads_pipelines" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."leads_pipelines";
CREATE POLICY "authenticated_update" ON public."leads_pipelines" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_delete" ON public."leads_stage_duplication_rules";
CREATE POLICY "authenticated_delete" ON public."leads_stage_duplication_rules" FOR DELETE TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_insert" ON public."leads_stage_duplication_rules";
CREATE POLICY "authenticated_insert" ON public."leads_stage_duplication_rules" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read_duplication_rules" ON public."leads_stage_duplication_rules";
CREATE POLICY "authenticated_read_duplication_rules" ON public."leads_stage_duplication_rules" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."leads_stage_duplication_rules";
CREATE POLICY "authenticated_update" ON public."leads_stage_duplication_rules" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_delete" ON public."leads_stages";
CREATE POLICY "authenticated_delete" ON public."leads_stages" FOR DELETE TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_insert" ON public."leads_stages";
CREATE POLICY "authenticated_insert" ON public."leads_stages" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_stages";
CREATE POLICY "authenticated_read" ON public."leads_stages" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."leads_stages";
CREATE POLICY "authenticated_update" ON public."leads_stages" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_stages_followups";
CREATE POLICY "authenticated_read" ON public."leads_stages_followups" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_stages_followups";
CREATE POLICY "authenticated_write" ON public."leads_stages_followups" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_tags";
CREATE POLICY "authenticated_read" ON public."leads_tags" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_tags";
CREATE POLICY "authenticated_write" ON public."leads_tags" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."leads_updates";
CREATE POLICY "authenticated_read" ON public."leads_updates" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."leads_updates";
CREATE POLICY "authenticated_write" ON public."leads_updates" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."meeting_followup_queue";
CREATE POLICY "authenticated_read" ON public."meeting_followup_queue" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."meeting_followup_queue";
CREATE POLICY "authenticated_write" ON public."meeting_followup_queue" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."meeting_records";
CREATE POLICY "authenticated_read" ON public."meeting_records" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."meeting_records";
CREATE POLICY "authenticated_write" ON public."meeting_records" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."meetings";
CREATE POLICY "authenticated_read" ON public."meetings" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."meetings";
CREATE POLICY "authenticated_write" ON public."meetings" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."meetings_followups";
CREATE POLICY "authenticated_read" ON public."meetings_followups" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."meetings_followups";
CREATE POLICY "authenticated_write" ON public."meetings_followups" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_delete" ON public."messages";
CREATE POLICY "authenticated_delete" ON public."messages" FOR DELETE TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_insert" ON public."messages";
CREATE POLICY "authenticated_insert" ON public."messages" FOR INSERT TO authenticated WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."messages";
CREATE POLICY "authenticated_update" ON public."messages" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."meta_lead_form_pages";
CREATE POLICY "authenticated_read" ON public."meta_lead_form_pages" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."meta_lead_forms";
CREATE POLICY "authenticated_read" ON public."meta_lead_forms" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."meta_lead_forms";
CREATE POLICY "authenticated_write" ON public."meta_lead_forms" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."notifications";
CREATE POLICY "authenticated_read" ON public."notifications" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."notifications";
CREATE POLICY "authenticated_write" ON public."notifications" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."omni_channel_configs";
CREATE POLICY "authenticated_read" ON public."omni_channel_configs" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."omni_outbound_webhooks";
CREATE POLICY "authenticated_read" ON public."omni_outbound_webhooks" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."omni_outbound_webhooks";
CREATE POLICY "authenticated_write" ON public."omni_outbound_webhooks" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_all" ON public."schedule_automations";
CREATE POLICY "authenticated_all" ON public."schedule_automations" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."score_categories";
CREATE POLICY "authenticated_read" ON public."score_categories" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."score_categories";
CREATE POLICY "authenticated_write" ON public."score_categories" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."score_category_items";
CREATE POLICY "authenticated_read" ON public."score_category_items" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."score_category_items";
CREATE POLICY "authenticated_write" ON public."score_category_items" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."score_matrix";
CREATE POLICY "authenticated_read" ON public."score_matrix" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."score_matrix";
CREATE POLICY "authenticated_write" ON public."score_matrix" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."score_settings";
CREATE POLICY "authenticated_read" ON public."score_settings" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."score_settings";
CREATE POLICY "authenticated_write" ON public."score_settings" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."sends";
CREATE POLICY "authenticated_read" ON public."sends" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."sends";
CREATE POLICY "authenticated_write" ON public."sends" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."sends_contacts";
CREATE POLICY "authenticated_read" ON public."sends_contacts" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."sends_contacts";
CREATE POLICY "authenticated_write" ON public."sends_contacts" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."sends_import_sessions";
CREATE POLICY "authenticated_read" ON public."sends_import_sessions" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."sends_import_sessions";
CREATE POLICY "authenticated_write" ON public."sends_import_sessions" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings";
CREATE POLICY "authenticated_read" ON public."settings" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_audit_log";
CREATE POLICY "authenticated_read" ON public."settings_audit_log" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_audit_log";
CREATE POLICY "authenticated_write" ON public."settings_audit_log" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_can_manage_business_hours" ON public."settings_business_hours";
CREATE POLICY "authenticated_can_manage_business_hours" ON public."settings_business_hours" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_elevenlabs";
CREATE POLICY "authenticated_read" ON public."settings_elevenlabs" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_omni_new_contact";
CREATE POLICY "authenticated_read" ON public."settings_omni_new_contact" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_omni_new_contact";
CREATE POLICY "authenticated_write" ON public."settings_omni_new_contact" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_schedules";
CREATE POLICY "authenticated_read" ON public."settings_schedules" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_schedules";
CREATE POLICY "authenticated_write" ON public."settings_schedules" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_system_modules";
CREATE POLICY "authenticated_read" ON public."settings_system_modules" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_system_modules";
CREATE POLICY "authenticated_write" ON public."settings_system_modules" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_teams";
CREATE POLICY "authenticated_read" ON public."settings_teams" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_teams";
CREATE POLICY "authenticated_write" ON public."settings_teams" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_teams_pipelines";
CREATE POLICY "authenticated_read" ON public."settings_teams_pipelines" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_teams_pipelines";
CREATE POLICY "authenticated_write" ON public."settings_teams_pipelines" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_teams_tags";
CREATE POLICY "authenticated_read" ON public."settings_teams_tags" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_teams_tags";
CREATE POLICY "authenticated_write" ON public."settings_teams_tags" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_users";
CREATE POLICY "authenticated_read" ON public."settings_users" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_users_teams";
CREATE POLICY "authenticated_read" ON public."settings_users_teams" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."settings_users_teams";
CREATE POLICY "authenticated_write" ON public."settings_users_teams" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."settings_whatsapp_channels";
CREATE POLICY "authenticated_read" ON public."settings_whatsapp_channels" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."tenant_api_keys";
CREATE POLICY "authenticated_read" ON public."tenant_api_keys" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."tenant_role_permissions";
CREATE POLICY "authenticated_read" ON public."tenant_role_permissions" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."tenant_roles";
CREATE POLICY "authenticated_read" ON public."tenant_roles" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."user_calcom_connections";
CREATE POLICY "authenticated_read" ON public."user_calcom_connections" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."user_calendar_connections";
CREATE POLICY "authenticated_read" ON public."user_calendar_connections" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."user_notification_preferences";
CREATE POLICY "authenticated_read" ON public."user_notification_preferences" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."user_notification_preferences";
CREATE POLICY "authenticated_write" ON public."user_notification_preferences" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_delete" ON public."webhook_logs";
CREATE POLICY "authenticated_delete" ON public."webhook_logs" FOR DELETE TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_update" ON public."webhook_logs";
CREATE POLICY "authenticated_update" ON public."webhook_logs" FOR UPDATE TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."webhooks";
CREATE POLICY "authenticated_read" ON public."webhooks" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."webhooks";
CREATE POLICY "authenticated_write" ON public."webhooks" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_read" ON public."whatsapp_templates";
CREATE POLICY "authenticated_read" ON public."whatsapp_templates" FOR SELECT TO authenticated USING ((select public.is_app_user()));
DROP POLICY IF EXISTS "authenticated_write" ON public."whatsapp_templates";
CREATE POLICY "authenticated_write" ON public."whatsapp_templates" FOR ALL TO authenticated USING ((select public.is_app_user())) WITH CHECK ((select public.is_app_user()));

COMMIT;